# Generated by Django 5.0.6 on 2024-07-04 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('time', models.TimeField(max_length=25, verbose_name='Время, когда надо выполнить привычку')),
                ('action', models.CharField(max_length=100, verbose_name='Действие, которое надо сделать')),
                ('duration', models.SmallIntegerField(verbose_name='Продолжительность в минутах')),
                ('is_daily', models.BooleanField(choices=[(True, 'Ежедневная'), (False, 'Еженедельная')], default=False, verbose_name='Периодичность')),
                ('is_good', models.BooleanField(choices=[(True, 'Приятная'), (False, 'Нет')], default=False, verbose_name='Приятная')),
                ('is_public', models.BooleanField(choices=[(True, 'Публичная'), (False, 'Нет')], default=True, verbose_name='Публичная')),
                ('prize', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('related', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits', verbose_name='Связанная с другой привычкой')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-id'],
            },
        ),
    ]
